hwam/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hwam'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('ou/', login_required(views.OUIndexView.as_view()),
        name='ou_index'),
    path('hw/', login_required(views.HWIndexView.as_view()),
        name='hw_index'),
    path('sw/', login_required(views.SWIndexView.as_view()),
        name='sw_index'),
    path('hw/search/', login_required(views.HWSearchView.as_view()),
        name='hw_search'),
    path('sw/search/', login_required(views.SWSearchView.as_view()),
        name='sw_search'),
    path('ou/<int:pk>/', login_required(views.OUDetailView.as_view()),
        name='ou_detail'),
    path('hw/<int:pk>/', login_required(views.HWDetailView.as_view()),
        name='hw_detail'),
    path('sw/<int:pk>/', login_required(views.SWDetailView.as_view()),
        name='sw_detail'),
    path('ou/add/', login_required(views.OUCreateView.as_view()),
        name='ou_create'),
    path('hw/add/', login_required(views.HWCreateView.as_view()),
        name='hw_create'),
    path('sw/add/', login_required(views.SWCreateView.as_view()),
        name='sw_create'),
    path('ou/<int:pk>/update/', login_required(views.OUUpdateView.as_view()),
        name='ou_update'),
    path('hw/<int:pk>/update/', login_required(views.HWUpdateView.as_view()),
        name='hw_update'),
    path('sw/<int:pk>/update/', login_required(views.SWUpdateView.as_view()),
        name='sw_update'),
    path('ou/<int:pk>/delete/', login_required(
        views.OUDeleteView.as_view()), name='ou_delete'),
    path('hw/<int:pk>/delete/', login_required(
        views.HWDeleteView.as_view()), name='hw_delete'),
    path('sw/<int:pk>/delete/', login_required(
        views.SWDeleteView.as_view()), name='sw_delete'),
]

siem/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'siem'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('help/parsing/', login_required(views.parse_help),
        name='parse_help'),
    path('help/rules/', login_required(views.rule_help),
        name='rule_help'),
    path('help/events/', login_required(views.event_help),
        name='event_help'),
    path('help/daemons/', login_required(views.daemon_help),
        name='daemon_help'),
    path('help/regex/', login_required(views.regex_help),
        name='regex_help'),
    path('events/', login_required(views.event_index), name='event_index'),
    path('events/log/<int:pk>/', login_required(
        views.LogEventDetailView.as_view()), name='logevent_detail'),
    path('events/log/', login_required(
        views.LogEventSearchView.as_view()), name='logevent_search'),
    path('events/rule/', login_required(
        views.RuleEventSearchView.as_view()), name='ruleevent_search'),
    path('events/rule/<int:pk>/', login_required(
        views.RuleEventDetailView.as_view()), name='ruleevent_detail'),
    path('rules/limit/', login_required(
        views.LRIndexView.as_view()), name='lr_index'),
    path('rules/limit/<int:pk>/', login_required(
        views.LRDetailView.as_view()), name='lr_detail'),
    path('rules/limit/add/', login_required(
        views.LRCreateView.as_view()), name='lr_create'),
    path('rules/limit/<int:pk>/update/', login_required(
        views.LRUpdateView.as_view()), name='lr_update'),
    path('rules/limit/<int:pk>/delete/', login_required(
        views.LRDeleteView.as_view()), name='lr_delete'),
    path('parsers/log/', login_required(
        views.LPIndexView.as_view()), name='lp_index'),
    path('parsers/log/<int:pk>/', login_required(
        views.LPDetailView.as_view()), name='lp_detail'),
    path('parsers/log/add/', login_required(
        views.LPCreateView.as_view()), name='lp_create'),
    path('parsers/log/<int:pk>/update/', login_required(
        views.LPUpdateView.as_view()), name='lp_update'),
    path('parsers/log/<int:pk>/delete/', login_required(
        views.LPDeleteView.as_view()), name='lp_delete'),
    path('parsers/helpers/', login_required(
        views.PHIndexView.as_view()), name='ph_index'),
    path('parsers/helpers/<int:pk>/', login_required(
        views.PHDetailView.as_view()), name='ph_detail'),
    path('parsers/helpers/add/', login_required(
        views.PHCreateView.as_view()), name='ph_create'),
    path('parsers/helpers/<int:pk>/update/', login_required(
        views.PHUpdateView.as_view()), name='ph_update'),
    path('parsers/helpers/<int:pk>/delete/', login_required(
        views.PHDeleteView.as_view()), name='ph_delete'),
]

siem/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from datetime import timedelta
from django.views.generic import ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import LogEvent
from .models import RuleEvent
from .models import LimitRule
from .models import LogEventParser, ParseHelper

# Create your views here.

def index(request):
    return render(request, 'siem/index.html')

def event_index(request):
    return render(request, 'siem/event_index.html')

def help_index(request):
    return render(request, 'siem/help_index.html')

def parse_help(request):
    return render(request, 'siem/help_parse.html')

def rule_help(request):
    return render(request, 'siem/help_rules.html')

def event_help(request):
    return render(request, 'siem/help_event.html')

def daemon_help(request):
    return render(request, 'siem/help_daemons.html')

def regex_help(request):
    return render(request, 'siem/help_regex.html')

class LogEventSearchView(PermissionRequiredMixin, ListView):
    model = LogEvent
    permission_required = 'siem.view_logevent'
    template_name = 'siem/logevent_search.html'
    context_object_name = 'event_list'
    paginate_by = 50
    def get_queryset(self):
        log_source_val = self.request.GET.get('log_source_filter')
        process_val = self.request.GET.get('process_filter')
        source_host_val = self.request.GET.get('source_host_filter')
        source_port_val = self.request.GET.get('source_port_filter')
        dest_host_val = self.request.GET.get('dest_host_filter')
        dest_port_val = self.request.GET.get('dest_port_filter')
        source_user_val = self.request.GET.get('source_user_filter')
        target_user_val = self.request.GET.get('target_user_filter')
        action_val = self.request.GET.get('action_filter')
        command_val = self.request.GET.get('command_filter')
        session_val = self.request.GET.get('session_filter')
        interface_val = self.request.GET.get('interface_filter')
        status_val = self.request.GET.get('status_filter')
        path_val = self.request.GET.get('path_filter')
        parameters_val = self.request.GET.get('parameters_filter')
        referrer_val = self.request.GET.get('referrer_filter')
        type_val = self.request.GET.get('type_filter')
        message_val = self.request.GET.get('message_filter')
        raw_val = self.request.GET.get('raw_filter')
        starttime_val = self.request.GET.get('starttime_filter')
        endtime_val = self.request.GET.get('endtime_filter')
        if not type_val: type_val = ''
        if not log_source_val: log_source_val = ''
        if not process_val: process_val = ''
        if not source_host_val: source_host_val = ''
        if not source_port_val: source_port_val = ''
        if not dest_host_val: dest_host_val = ''
        if not dest_port_val: dest_port_val = ''
        if not source_user_val: source_user_val = ''
        if not target_user_val: target_user_val = ''
        if not action_val: action_val = ''
        if not command_val: command_val = ''
        if not session_val: session_val = ''
        if not interface_val: interface_val = ''
        if not status_val: status_val = ''
        if not path_val: path_val = ''
        if not parameters_val: parameters_val = ''
        if not referrer_val: referrer_val = ''
        if not message_val: message_val = ''
        if not raw_val: raw_val = ''
        if not starttime_val and not endtime_val:
            starttime_val = (timezone.localtime(timezone.now()) - \
                    timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S')
        if endtime_val and starttime_val:
            new_context = LogEvent.objects.filter(
                parsed_at__gte=starttime_val,
                parsed_at__lte=endtime_val,
                event_type__iregex=type_val,
                log_source__iregex=log_source_val,
                source_process__iregex=process_val,
                source_host__iregex=source_host_val,
                source_port__iregex=source_port_val,
                dest_host__iregex=dest_host_val,
                dest_port__iregex=dest_port_val,
                source_user__iregex=source_user_val,
                target_user__iregex=target_user_val,
                action__iregex=action_val,
                command__iregex=command_val,
                sessionid__iregex=session_val,
                interface__iregex=interface_val,
                status__iregex=status_val,
                message__iregex=message_val,
                raw_text__iregex=raw_val).order_by('-id')
        elif endtime_val and not starttime_val:
            new_context = LogEvent.objects.filter(
                parsed_at__lte=endtime_val,
                event_type__iregex=type_val,
                log_source__iregex=log_source_val,
                source_process__iregex=process_val,
                source_host__iregex=source_host_val,
                source_port__iregex=source_port_val,
                dest_host__iregex=dest_host_val,
                dest_port__iregex=dest_port_val,
                source_user__iregex=source_user_val,
                target_user__iregex=target_user_val,
                action__iregex=action_val,
                command__iregex=command_val,
                sessionid__iregex=session_val,
                interface__iregex=interface_val,
                status__iregex=status_val,
                message__iregex=message_val,
                raw_text__iregex=raw_val).order_by('-id')
        else:
            new_context = LogEvent.objects.filter(
                parsed_at__gte=starttime_val,
                event_type__iregex=type_val,
                log_source__iregex=log_source_val,
                source_process__iregex=process_val,
                source_host__iregex=source_host_val,
                source_port__iregex=source_port_val,
                dest_host__iregex=dest_host_val,
                dest_port__iregex=dest_port_val,
                source_user__iregex=source_user_val,
                target_user__iregex=target_user_val,
                action__iregex=action_val,
                command__iregex=command_val,
                sessionid__iregex=session_val,
                interface__iregex=interface_val,
                status__iregex=status_val,
                message__iregex=message_val,
                raw_text__iregex=raw_val).order_by('-id')
        #else:
        #    new_context = LogEvent.objects.filter(
        #        event_type__iregex=type_val,
        #        log_source__iregex=log_source_val,
        #        source_process__iregex=process_val,
        #        source_host__iregex=source_host_val,
        #        source_port__iregex=source_port_val,
        #        dest_host__iregex=dest_host_val,
        #        dest_port__iregex=dest_port_val,
        #        source_user__iregex=source_user_val,
        #        target_user__iregex=target_user_val,
        #        action__iregex=action_val,
        #        command__iregex=command_val,
        #        sessionid__iregex=session_val,
        #        interface__iregex=interface_val,
        #        status__iregex=status_val,
        #        message__iregex=message_val,
        #        raw_text__iregex=raw_val).order_by('-id')
        return new_context
    def get_context_data(self, **kwargs):
        context = super(LogEventSearchView,self).get_context_data(**kwargs)
        context['log_source_filter'] = self.request.GET.get(
                'log_source_filter', '')
        context['process_filter'] = self.request.GET.get('process_filter', '')
        context['source_host_filter'] = self.request.GET.get(
                'source_host_filter', '')
        context['source_port_filter'] = self.request.GET.get(
                'source_port_filter', '')
        context['dest_host_filter'] = self.request.GET.get(
                'dest_host_filter', '')
        context['dest_port_filter'] = self.request.GET.get(
                'dest_port_filter', '')
        context['source_user_filter'] = self.request.GET.get(
                'source_user_filter', '')
        context['target_user_filter'] = self.request.GET.get(
                'target_user_filter', '')
        context['action_filter'] = self.request.GET.get(
                'action_filter', '')
        context['command_filter'] = self.request.GET.get(
                'command_filter', '')
        context['session_filter'] = self.request.GET.get(
                'session_filter', '')
        context['interface_filter'] = self.request.GET.get(
                'interface_filter', '')
        context['status_filter'] = self.request.GET.get(
                'status_filter', '')
        context['path_filter'] = self.request.GET.get(
                'path_filter', '')
        context['parameters_filter'] = self.request.GET.get(
                'parameters_filter', '')
        context['referrer_filter'] = self.request.GET.get(
                'referrer_filter', '')
        context['type_filter'] = self.request.GET.get(
                'type_filter', '')
        context['message_filter'] = self.request.GET.get(
                'message_filter', '')
        context['raw_filter'] = self.request.GET.get(
                'raw_filter', '')
        context['starttime_filter'] = self.request.GET.get(
                'starttime_filter', '')
        context['endtime_filter'] = self.request.GET.get(
                'endtime_filter', '')
        if not context['starttime_filter'] and \
                not context['endtime_filter']:
            context['starttime_filter'] = (
                    timezone.localtime(timezone.now()) - \
                    timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S')
        context['order'] = 'desc'
        return context

siem/templates/siem/help_index.html
{% extends "siem/base.html" %}

{% block sub-title %}Documentation | {% endblock %}

{% block content-main %}

<h1>Documentation</h1>

<ul>
    <li><a href="{% url 'siem:parse_help' %}">Parsing</a><ul>
        <li><a href="{% url 'siem:parse_help' %}#daemon">Parse Daemon</a></li>
        <li><a href="{% url 'siem:parse_help' %}#event">Event Parsing</a><ul>
            <li><a href="{% url 'siem:parse_help' %}#parsers">Parsers</a></li>
            <li><a href="{% url 'siem:parse_help' %}#helpers">Parse Helpers</a></li>
            </ul>
        </li>
        <li><a href="{% url 'siem:parse_help' %}#configuration">Configuration</a><ul>
        </ul>
    </li>
    <li><a href="{% url 'siem:rule_help' %}">Rules</a><ul>
        <li><a href="{% url 'siem:rule_help' %}#daemon">Sentry Daemon</a></li>
        <li><a href="{% url 'siem:rule_help' %}#limitrules">Limit Rules</a><ul>
            <li><a href="{% url 'siem:rule_help' %}#rulevlog">Rule vs. Log Events</a></li>
            <li><a href="{% url 'siem:rule_help' %}#filters">Filters</a></li>
            <li><a href="{% url 'siem:rule_help' %}#match-lists">Match Lists</a></li>
            <li><a href="{% url 'siem:rule_help' %}#reverse-matching">Reverse Matching</a></li>
            <li><a href="{% url 'siem:rule_help' %}#magnitude">Magnitude Calculation</a></li>
            </ul>
        </li>
        </ul>
    </li>
    <li><a href="{% url 'siem:event_help' %}">Events</a><ul>
        <li><a href="{% url 'siem:event_help' %}#logevent">Anatomy of a Log Event</a></li>
        <li><a href="{% url 'siem:event_help' %}#ruleevent">Anatomy of a Rule Event</a></li>
        </ul></li>
    <li><a href="{% url 'siem:daemon_help' %}">Daemons</a></li>
    <li><a href="{% url 'siem:regex_help' %}">Regex Tips</a></li>
</ul>

{% endblock %}

siem/templates/siem/help_parse.html
{% extends "siem/base.html" %}

{% block sub-title %}Parsing Documentation | {% endblock %}

{% block content-main %}

<h1>Parsing Documentation</h1>

<ul>
    <li><a href="#daemon">Parse Daemon</a></li>
    <li><a href="#event">Event Parsing</a><ul>
        <li><a href="#parsers">Parsers</a></li>
        <li><a href="#helpers">Parse Helpers</a></li>
        </ul>
    </li>
    <li><a href="#configuration">Configuration</a></li>
</ul>

<hr>
<a name="daemon"></a>
<h2>Parse Daemon</h2>
<p>The parse daemon is the program that parses log files into log events in the LogESP database. The files it parses are defined in the parser configuration file, at <b>config/parser.conf</b> in the repository. This configuration file also defines which event type to assign to events, which parser to use, the lifespan of the events, and optionally which parse helper type to use, and which syslog facility to assign.</p>

<p>For more on running the parse daemon, see the <a href="{% url 'siem:daemon_help' %}">daemon documentation</a>.</p>
<hr>
<a name="event"></a>
<h2>Event Parsing</h2>
<p>The parse daemon parses events using instructions from a parser, and optionally a group of parse helpers. The parser parses basic fields that are present in all events in the file being parsed, and parse helpers can be used to parse extra fields that aren't present in every single event.</p>

<a name="parsers"></a>
<h3>Parsers</h3>
<p>Parsers provide the parse daemon with instructions for parsing fields from events. Along with a name and description, parsers contain sets of matching information. Each set consists of a regular expression, and a comma-separated list of fields pulled by that regular expression. The fields can be any log event attribute (e.g. source_host, dest_host, target_user; see <a href="{% url 'siem:event_help' %}#logevent">Anatomy of a Log Event</a>)</p>

<p>Each parser can have two sets of regex/field pairs: a primary, and a backup. If the primary regular expression doesn't find a match, the backup will be tried.</p>

<a name="helpers"></a>
<h3>Parse Helpers</h3>
<p>Parse helpers contain a regular expression and a comma-separated list of fields, similar to a parser. After parsing the main fields, the parse daemon tries each parse helper (of the helper type defined in the config file). If it finds a match, it pulls out extra fields; if not, it just moves on. Parse helpers are useful for parsing regular expressions and fields that aren't present in every single event.</p>
<hr>
<a name="configuration"></a>
<h2>Configuration</h2>
<p>The parser configuration file at `config/parser.conf` has one section per file. Here is an example section:</p>

<pre>
[auth]
filename=/var/log/auth.log
event_type=auth
parser=syslog
helper_type=auth
local_lifespan_days=185
backup_lifespan_days=366
</pre>

<ul>
    <li>The section name must be unique, and should be meaningful; it is used in parser error logs.</li>
    <li><b>filename</b> - the file to follow</li>
    <li><b>event_type</b>` - the <b>event_type</b> to set for parsed events</li>
    <li><b>parser</b>` - the parser to use when parsing events</li>
    <li><b>helper_type</b>` - the type of parse helpers to use for additional fields</li>
    <li><b>local_lifespan_days</b>` - the lifespan, in days, for the locally stored copy</li>
    <li><b>backup_lifespan_days</b>` - the lifespan, in days, for the backup copy</li>
</ul>

<p>A few more settings are available, in addition to the ones used above:</p>
<ul>
    <li><b>`log_source</b>` - for logs that don't indicate the originating host (e.g. web access logs)</li>
    <li><b>source_process</b> - <b>source_process</b> to assign to all events</li>

    <li><b>`facility</b>` - sets the syslog facility (0-23)</li>
</ul>

{% endblock %}

siem/templates/siem/help_regex.html
{% extends "siem/base.html" %}

{% block sub-title %}Regex Tips | {% endblock %}

{% block content-main %}

<h1>Regex Tips</h1>
<p>Regular expression tips for use with LogESP</p>
<ul>
    <li><a href="#search">Event Parsing</a></li><ul>
</ul>

<a name="searches"></a>
<h2>Searches and Rules</h2>
<h3>Reminders</h3>
<ul>
    <li>Search/rule regex is case insensitive</li>
</ul>

<h3>Tricks</h3>
<p>Match either EXPRESSION1 or EXPRESSION2:</p>
<pre>(EXPRESSION1|EXPRESSION2)</pre>

<p>Match an expression literally (not just any field that contains it):</p>
<pre>^EXPRESSION$</pre>

<p>Filter out an expression in a field:</p>
<pre>^(?!EXPRESSION)</pre>

{% endblock %}

siem/templates/siem/logeventparser_form.html
{% extends "siem/base.html" %}

{% block sub-title %}Add Parser | {% endblock %}

{% block content-main %}

<h1>Add Log Event Parser</h1>
{% if form.errors %}
<p>There were some errors.</p>

<ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.label_tag }}: {{ field.errors }}</li>
    {% endif %}
    {% endfor %}
</ul>

{% endif %}

<form action="" method="post">{% csrf_token %}
    <table>
        <tr>
            <th>Attribute</th><th>Setting</th><th class="left">Description</th>
        </tr>
        <tr>
            <td class="right">Name</td><td>{{ form.name }}</td><td>The parser name.</td>
        </tr>
        <tr>
            <td class="right">Desc</td><td>{{ form.desc }}</td><td>A description of the parser.</td>
        </tr>
        <tr>
            <td class="right">Match Regex</td><td>{{ form.match_regex }}</td><td>The regular expression for finding attributes.</td>
        </tr>
        <tr>
            <td class="right">Fields</td><td>{{ form.fields }}</td><td>The fields parsed by the regular expression.</td>
        </tr>
        <tr>
            <td class="right">Backup Match Regex</td><td>{{ form.backup_match_regex }}</td><td>A backup regular expression, in case the first one fails.</td>
        </tr>
        <tr>
            <td class="right">Backup Fields</td><td>{{ form.backup_fields }}</td><td>The fields parsed by the backup regular expression.</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

siem/templates/siem/lp_index.html
{% extends "siem/base.html" %}

{% block sub-title %}Parsers | {% endblock %}

{% block content-main %}

<h1>Log Event Parsers</h1>
<a href="{% url 'siem:lp_create' %}">Add</a>

{% if lp_list %}
    <table>
        <tr><th>Name</th><th>Built-<br>in?</th><th>Fields</th></tr>
        {% for lp in lp_list %}
            <tr>
                <td><a href="{% url 'siem:lp_detail' lp.id %}">
                        {{ lp }}</a></td>
                <td>{{ lp.is_builtin }}</td>
                <td>{{ lp.fields }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No limit rules.</p>
{% endif %}

{% endblock %}

siem/templates/siem/lr_delete.html
{% extends "siem/base.html" %}

{% block sub-title %}Delete Limit Rule | {% endblock %}

{% block content-main %}

<h1>Delete Limit Rule</h1>

<p>Are you sure you want to delete limit rule {{ lr }}?</p>

<form action="{% url 'siem:lr_delete' lr.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'siem:lr_detail' lr.id %}">Cancel</a>
</form>

{% endblock %}

siem/templates/siem/lr_index.html
{% extends "siem/base.html" %}

{% block sub-title %}Limit Rules | {% endblock %}

{% block content-main %}

<h1>Limit Rules</h1>
<a href="{% url 'siem:lr_create' %}">Add</a>

{% if lr_list %}
    <table>
        <tr><th>Rule Name</th><th>Event<br>Type</th>
            <th>Rule<br>Events?</br><th>Enabled?</th>
                <th>Built-<br>in?</th></tr>
        {% for lr in lr_list %}
            <tr><td><a href="{% url 'siem:lr_detail' lr.id %}">
                    {{ lr }}</a></td>
                <td>{{ lr.event_type }}</td>
                <td>{{ lr.rule_events }}</td>
                <td>{{ lr.is_enabled }}</td>
                <td>{{ lr.is_builtin }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No limit rules.</p>
{% endif %}

{% endblock %}

siem/templates/siem/ph_detail.html
{% extends "siem/base.html" %}

{% block sub-title %}Parse Helper - {{ ph }} | {% endblock %}

{% block content-main %}

<h1>{{ ph }} (Parse Helper)</h1>
<a href="{% url 'siem:ph_update' ph.id %}">Edit</a>
&middot;
<a href="{% url 'siem:ph_delete' ph.id %}">Delete</a>
&middot;
<a href="{% url 'siem:ph_index' %}">Index</a>

<table>
    <tr>
        <th>Attribute</th><th>Setting</th><th class="left">Description</th>
    </tr>
    <tr>
        <td class="right">ID</td><td>{{ ph.id }}</td><td>The parse helper's internal ID</td>
    </tr>
    <tr>
        <td class="right">Built-in?</td><td>{{ ph.is_builtin }}</td><td>Whether the parse helper is built-in to LogESP.</td>
    </tr>
    <tr>
        <td class="right">Name</td><td>{{ ph.name }}</td><td>The parse helper name.</td>
    </tr>
    <tr>
        <td class="right">Desc</td><td>{{ ph.desc }}</td><td>A description of the parse helper.</td>
    </tr>
    <tr>
        <td class="right">Helper Type</td><td>{{ ph.helper_type }}</td><td>The parse helper type that this helper belongs to.</td>
    </tr>
    <tr>
        <td class="right">Match Regex</td><td>{{ ph.match_regex }}</td><td>The regular expression for finding attributes.</td>
    </tr>
    <tr>
        <td class="right">Fields</td><td>{{ ph.fields }}</td><td>The fields parsed by the regular expression</td>
    </tr>
</table>

{% endblock %}

siem/templates/siem/ph_index.html
{% extends "siem/base.html" %}

{% block sub-title %}Parser Helpers | {% endblock %}

{% block content-main %}

<h1>Parse Helpers</h1>
<a href="{% url 'siem:ph_create' %}">Add</a>

{% if ph_list %}
    <table>
        <tr><th>Name</th><th>Type</th><th>Fields</th>
            <th>Built-<br>in</th></tr>
        {% for ph in ph_list %}
            <tr>
                <td><a href="{% url 'siem:ph_detail' ph.id %}">
                        {{ ph }}</a></td>
                <td>{{ ph.helper_type }}</td>
                <td>{{ ph.fields }}</td>
                <td>{{ ph.is_builtin }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No parse helpers.</p>
{% endif %}

{% endblock %}

siem/templates/siem/ruleevent_detail.html
{% extends "siem/base.html" %}

{% block sub-title %}Rule-Based Event | {% endblock %}

{% block content-main %}

<h1>Rule-Based Event</h1>
<a href="{% url 'siem:ruleevent_search' %}">Index</a>

<ul>
    <li>ID: {{ event.id }}</li>
    <li>Date Stamp: {{ event.date_stamp|date:"Y M d H:i:s" }}</li>
    <li>Time Zone: {{ event.time_zone }}</li>
    <li>SIEM EOL Date: {{ event.eol_date_local|date:"Y M d" }}</li>
    <li>Backup EOL Date: {{ event.eol_date_backup|date:"Y M d" }}</li>
    <li>Rule Category: {{ event.rule_category }}</li>
    <li>Event Type: {{ event.event_type }}</li>
    <li>Source Rule:
        <a href="{% url 'siem:lr_detail' event.source_rule.id %}">{{ event.source_rule }}</a></li>
    <li>Magnitude: {{ event.magnitude }}</li>
    <li>Event Count: {{ event.event_count }}</li>
    <li>Event Limit: {{ event.event_limit }}</li>
    <li>Time Interval: {{ event.time_int }} minutes</li>
    <li>Severity: {{ event.severity }}</li>
    <li>Log Source Count: {{ event.log_source_count }}</li>
    <li>Source Host Count: {{ event.source_host_count }}</li>
    <li>Dest Host Count: {{ event.dest_host_count }}</li>
    <li>Message: {{ event.message }}</li>
    <li>Source Log Events:
        {%for s in event.source_ids_log.all %}
            <a href="{% url 'siem:logevent_detail' s.id %}">{{ s.id }}</a>
        {% endfor %}
    </li>
    <li>Source Rule Events:
        {%for s in event.source_ids_rule.all %}
            <a href="{% url 'siem:ruleevent_detail' s.id %}">{{ s.id }}</a>
        {% endfor %}
    </li>
</ul>

{% endblock %}