hwam/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hwam'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('ou/', login_required(views.OUIndexView.as_view()),
        name='ou_index'),
    path('hw/', login_required(views.HWIndexView.as_view()),
        name='hw_index'),
    path('sw/', login_required(views.SWIndexView.as_view()),
        name='sw_index'),
    path('hw/search/', login_required(views.HWSearchView.as_view()),
        name='hw_search'),
    path('sw/search/', login_required(views.SWSearchView.as_view()),
        name='sw_search'),
    path('ou/<int:pk>/', login_required(views.OUDetailView.as_view()),
        name='ou_detail'),
    path('hw/<int:pk>/', login_required(views.HWDetailView.as_view()),
        name='hw_detail'),
    path('sw/<int:pk>/', login_required(views.SWDetailView.as_view()),
        name='sw_detail'),
    path('ou/add/', login_required(views.OUCreateView.as_view()),
        name='ou_create'),
    path('hw/add/', login_required(views.HWCreateView.as_view()),
        name='hw_create'),
    path('sw/add/', login_required(views.SWCreateView.as_view()),
        name='sw_create'),
    path('ou/<int:pk>/update/', login_required(views.OUUpdateView.as_view()),
        name='ou_update'),
    path('hw/<int:pk>/update/', login_required(views.HWUpdateView.as_view()),
        name='hw_update'),
    path('sw/<int:pk>/update/', login_required(views.SWUpdateView.as_view()),
        name='sw_update'),
    path('ou/<int:pk>/delete/', login_required(
        views.OUDeleteView.as_view()), name='ou_delete'),
    path('hw/<int:pk>/delete/', login_required(
        views.HWDeleteView.as_view()), name='hw_delete'),
    path('sw/<int:pk>/delete/', login_required(
        views.SWDeleteView.as_view()), name='sw_delete'),
]

risk/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'risk'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('help/adv_threat', login_required(views.help_adv_threat),
        name='help_adv_threat'),
    path('help/nonadv_threat', login_required(views.help_nonadv_threat),
        name='help_nonadv_threat'),
    path('at/', login_required(views.ATEIndexView.as_view()),
        name='ate_index'),
    path('nt/', login_required(views.NTEIndexView.as_view()),
        name='nte_index'),
    path('at/sources/', login_required(views.ATSIndexView.as_view()),
        name='ats_index'),
    path('nt/sources/', login_required(views.NTSIndexView.as_view()),
        name='nts_index'),
    path('at/vulns/', login_required(views.VulnIndexView.as_view()),
        name='vuln_index'),
    path('nt/conds/', login_required(views.CondIndexView.as_view()),
        name='cond_index'),
    path('impacts/', login_required(views.ImpactIndexView.as_view()),
        name='impact_index'),
    path('responses/', login_required(views.ResponseIndexView.as_view()),
        name='response_index'),
    path('at/events/<int:pk>/', login_required(
        views.ATEDetailView.as_view()),
        name='ate_detail'),
    path('nt/events/<int:pk>/', login_required(
        views.NTEDetailView.as_view()),
        name='nte_detail'),
    path('at/sources/<int:pk>/', login_required(
        views.ATSDetailView.as_view()),
        name='ats_detail'),
    path('nt/sources/<int:pk>/', login_required(
        views.NTSDetailView.as_view()),
        name='nts_detail'),
    path('at/vulns/<int:pk>/', login_required(
        views.VulnDetailView.as_view()),
        name='vuln_detail'),
    path('nt/conds/<int:pk>/', login_required(
        views.CondDetailView.as_view()),
        name='cond_detail'),
    path('impacts/<int:pk>/', login_required(
        views.ImpactDetailView.as_view()),
        name='impact_detail'),
    path('response/<int:pk>/', login_required(
        views.ResponseDetailView.as_view()),
        name='response_detail'),
    path('at/events/add/', login_required(views.ATECreateView.as_view()),
        name='ate_create'),
    path('nt/events/add/', login_required(views.NTECreateView.as_view()),
        name='nte_create'),
    path('at/sources/add/', login_required(views.ATSCreateView.as_view()),
        name='ats_create'),
    path('nt/sources/add/', login_required(views.NTSCreateView.as_view()),
        name='nts_create'),
    path('at/vulns/add/', login_required(views.VulnCreateView.as_view()),
        name='vuln_create'),
    path('nt/conds/add/', login_required(views.CondCreateView.as_view()),
        name='cond_create'),
    path('impacts/add/', login_required(views.ImpactCreateView.as_view()),
        name='impact_create'),
    path('responses/add/', login_required(
        views.ResponseCreateView.as_view()),
        name='response_create'),
    path('at/events/<int:pk>/update/',
        login_required(views.ATEUpdateView.as_view()),
        name='ate_update'),
    path('nt/events/<int:pk>/update/',
        login_required(views.NTEUpdateView.as_view()),
        name='nte_update'),
    path('at/sources/<int:pk>/update/',
        login_required(views.ATSUpdateView.as_view()),
        name='ats_update'),
    path('nt/sources/<int:pk>/update/',
        login_required(views.NTSUpdateView.as_view()),
        name='nts_update'),
    path('at/vulns/<int:pk>/update/',
        login_required(views.VulnUpdateView.as_view()),
        name='vuln_update'),
    path('nt/conds/<int:pk>/update/',
        login_required(views.CondUpdateView.as_view()),
        name='cond_update'),
    path('impacts/<int:pk>/update/',
        login_required(views.ImpactUpdateView.as_view()),
        name='impact_update'),
    path('responses/<int:pk>/update/',
        login_required(views.ResponseUpdateView.as_view()),
        name='response_update'),
    path('at/events/<int:pk>/delete/',
        login_required(views.ATEDeleteView.as_view()),
        name='ate_delete'),
    path('nt/events/<int:pk>/delete/',
        login_required(views.NTEDeleteView.as_view()),
        name='nte_delete'),
    path('at/sources/<int:pk>/delete/',
        login_required(views.ATSDeleteView.as_view()),
        name='ats_delete'),
    path('nt/sources/<int:pk>/delete/',
        login_required(views.NTSDeleteView.as_view()),
        name='nts_delete'),
    path('at/vulns/<int:pk>/delete/',
        login_required(views.VulnDeleteView.as_view()),
        name='vuln_delete'),
    path('nt/conds/<int:pk>/delete/',
        login_required(views.CondDeleteView.as_view()),
        name='cond_delete'),
    path('impacts/<int:pk>/delete/',
        login_required(views.ImpactDeleteView.as_view()),
        name='impact_delete'),
    path('responses/<int:pk>/delete/',
        login_required(views.ResponseDeleteView.as_view()),
        name='response_delete'),
]

siem/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'siem'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('help/parsing/', login_required(views.parse_help),
        name='parse_help'),
    path('help/rules/', login_required(views.rule_help),
        name='rule_help'),
    path('help/events/', login_required(views.event_help),
        name='event_help'),
    path('help/daemons/', login_required(views.daemon_help),
        name='daemon_help'),
    path('help/regex/', login_required(views.regex_help),
        name='regex_help'),
    path('events/', login_required(views.event_index), name='event_index'),
    path('events/log/<int:pk>/', login_required(
        views.LogEventDetailView.as_view()), name='logevent_detail'),
    path('events/log/', login_required(
        views.LogEventSearchView.as_view()), name='logevent_search'),
    path('events/rule/', login_required(
        views.RuleEventSearchView.as_view()), name='ruleevent_search'),
    path('events/rule/<int:pk>/', login_required(
        views.RuleEventDetailView.as_view()), name='ruleevent_detail'),
    path('rules/limit/', login_required(
        views.LRIndexView.as_view()), name='lr_index'),
    path('rules/limit/<int:pk>/', login_required(
        views.LRDetailView.as_view()), name='lr_detail'),
    path('rules/limit/add/', login_required(
        views.LRCreateView.as_view()), name='lr_create'),
    path('rules/limit/<int:pk>/update/', login_required(
        views.LRUpdateView.as_view()), name='lr_update'),
    path('rules/limit/<int:pk>/delete/', login_required(
        views.LRDeleteView.as_view()), name='lr_delete'),
    path('parsers/log/', login_required(
        views.LPIndexView.as_view()), name='lp_index'),
    path('parsers/log/<int:pk>/', login_required(
        views.LPDetailView.as_view()), name='lp_detail'),
    path('parsers/log/add/', login_required(
        views.LPCreateView.as_view()), name='lp_create'),
    path('parsers/log/<int:pk>/update/', login_required(
        views.LPUpdateView.as_view()), name='lp_update'),
    path('parsers/log/<int:pk>/delete/', login_required(
        views.LPDeleteView.as_view()), name='lp_delete'),
    path('parsers/helpers/', login_required(
        views.PHIndexView.as_view()), name='ph_index'),
    path('parsers/helpers/<int:pk>/', login_required(
        views.PHDetailView.as_view()), name='ph_detail'),
    path('parsers/helpers/add/', login_required(
        views.PHCreateView.as_view()), name='ph_create'),
    path('parsers/helpers/<int:pk>/update/', login_required(
        views.PHUpdateView.as_view()), name='ph_update'),
    path('parsers/helpers/<int:pk>/delete/', login_required(
        views.PHDeleteView.as_view()), name='ph_delete'),
]

templates/base.html
{% load static %}


<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <title>{% block title %}{% endblock %}LogESP</title>
</head>
<body>
    <div class="topbar">
        {% include "navigation.html" %}
        {% block navbar %}
        {% endblock %}
    </div>
    
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer">
        {% include "footer.html" %}
    </div>
</body>

templates/footer.html
<center>
    CT &middot;
    <a href="{% url 'license' %}">MIT License</a>
</center>

templates/index.html
{% extends "base.html" %}

{% block title %}Index | {% endblock %}

{% block content %}

<h1>LogESP</h1>
<p>Version {{ version }}</p>

<ul>
    <li><a href="{% url 'hwam:index' %}">Assets</a>
        &middot; Asset Management</li>
    <li><a href="{% url 'risk:index' %}">Risk</a>
        &middot; Risk Management</li>
    <li><a href="{% url 'siem:index' %}">SIEM</a>
        &middot; Security Information and Event Management</li>
</ul>

{% endblock %}

templates/license.html
{% extends "base.html" %}

{% block title %}License | {% endblock %}

{% block content %}

<center><div class="license"><pre>

MIT License

Copyright (c) 2017 Dan Persons (dpersonsdev@gmail.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

</pre></div></center>

{% endblock %}

templates/navigation.html
    <div class="navbar">
        <div class="navbar-content">
            <div class="navbar-left">
            <a class="navbar" href="{% url 'index' %}"><b>LogESP</b></a>
            &middot;
            <a class="navbar" href="{% url 'hwam:index' %}">Assets</a>
            &middot;
            <a class="navbar" href="{% url 'risk:index' %}">Risk</a>
            &middot;
            <a class="navbar" href="{% url 'siem:index' %}">SIEM</a>
            </div>
            <div class="navbar-right">
            {% if user.is_staff %}
                <a class="navbar" href="{% url 'admin:index' %}">Admin</a>
                &middot;
            {% endif %}
            {% if user.is_authenticated %}
                <a class="navbar" href="{% url 'password_change' %}">
                    Change Password</a>
                &middot;
                <a class="navbar" href="{% url 'logout' %}?next={% url 'index' %}">
                    Logout</a>
            {% else %}
                <a class="navbar" href="{% url 'login' %}?next={% url 'index' %}">
                    Login</a>
            {% endif %}
            </div>
        </div>
    </div>