hwam/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hwam'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('ou/', login_required(views.OUIndexView.as_view()),
        name='ou_index'),
    path('hw/', login_required(views.HWIndexView.as_view()),
        name='hw_index'),
    path('sw/', login_required(views.SWIndexView.as_view()),
        name='sw_index'),
    path('hw/search/', login_required(views.HWSearchView.as_view()),
        name='hw_search'),
    path('sw/search/', login_required(views.SWSearchView.as_view()),
        name='sw_search'),
    path('ou/<int:pk>/', login_required(views.OUDetailView.as_view()),
        name='ou_detail'),
    path('hw/<int:pk>/', login_required(views.HWDetailView.as_view()),
        name='hw_detail'),
    path('sw/<int:pk>/', login_required(views.SWDetailView.as_view()),
        name='sw_detail'),
    path('ou/add/', login_required(views.OUCreateView.as_view()),
        name='ou_create'),
    path('hw/add/', login_required(views.HWCreateView.as_view()),
        name='hw_create'),
    path('sw/add/', login_required(views.SWCreateView.as_view()),
        name='sw_create'),
    path('ou/<int:pk>/update/', login_required(views.OUUpdateView.as_view()),
        name='ou_update'),
    path('hw/<int:pk>/update/', login_required(views.HWUpdateView.as_view()),
        name='hw_update'),
    path('sw/<int:pk>/update/', login_required(views.SWUpdateView.as_view()),
        name='sw_update'),
    path('ou/<int:pk>/delete/', login_required(
        views.OUDeleteView.as_view()), name='ou_delete'),
    path('hw/<int:pk>/delete/', login_required(
        views.HWDeleteView.as_view()), name='hw_delete'),
    path('sw/<int:pk>/delete/', login_required(
        views.SWDeleteView.as_view()), name='sw_delete'),
]

risk/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'risk'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('help/adv_threat', login_required(views.help_adv_threat),
        name='help_adv_threat'),
    path('help/nonadv_threat', login_required(views.help_nonadv_threat),
        name='help_nonadv_threat'),
    path('at/', login_required(views.ATEIndexView.as_view()),
        name='ate_index'),
    path('nt/', login_required(views.NTEIndexView.as_view()),
        name='nte_index'),
    path('at/sources/', login_required(views.ATSIndexView.as_view()),
        name='ats_index'),
    path('nt/sources/', login_required(views.NTSIndexView.as_view()),
        name='nts_index'),
    path('at/vulns/', login_required(views.VulnIndexView.as_view()),
        name='vuln_index'),
    path('nt/conds/', login_required(views.CondIndexView.as_view()),
        name='cond_index'),
    path('impacts/', login_required(views.ImpactIndexView.as_view()),
        name='impact_index'),
    path('responses/', login_required(views.ResponseIndexView.as_view()),
        name='response_index'),
    path('at/events/<int:pk>/', login_required(
        views.ATEDetailView.as_view()),
        name='ate_detail'),
    path('nt/events/<int:pk>/', login_required(
        views.NTEDetailView.as_view()),
        name='nte_detail'),
    path('at/sources/<int:pk>/', login_required(
        views.ATSDetailView.as_view()),
        name='ats_detail'),
    path('nt/sources/<int:pk>/', login_required(
        views.NTSDetailView.as_view()),
        name='nts_detail'),
    path('at/vulns/<int:pk>/', login_required(
        views.VulnDetailView.as_view()),
        name='vuln_detail'),
    path('nt/conds/<int:pk>/', login_required(
        views.CondDetailView.as_view()),
        name='cond_detail'),
    path('impacts/<int:pk>/', login_required(
        views.ImpactDetailView.as_view()),
        name='impact_detail'),
    path('response/<int:pk>/', login_required(
        views.ResponseDetailView.as_view()),
        name='response_detail'),
    path('at/events/add/', login_required(views.ATECreateView.as_view()),
        name='ate_create'),
    path('nt/events/add/', login_required(views.NTECreateView.as_view()),
        name='nte_create'),
    path('at/sources/add/', login_required(views.ATSCreateView.as_view()),
        name='ats_create'),
    path('nt/sources/add/', login_required(views.NTSCreateView.as_view()),
        name='nts_create'),
    path('at/vulns/add/', login_required(views.VulnCreateView.as_view()),
        name='vuln_create'),
    path('nt/conds/add/', login_required(views.CondCreateView.as_view()),
        name='cond_create'),
    path('impacts/add/', login_required(views.ImpactCreateView.as_view()),
        name='impact_create'),
    path('responses/add/', login_required(
        views.ResponseCreateView.as_view()),
        name='response_create'),
    path('at/events/<int:pk>/update/',
        login_required(views.ATEUpdateView.as_view()),
        name='ate_update'),
    path('nt/events/<int:pk>/update/',
        login_required(views.NTEUpdateView.as_view()),
        name='nte_update'),
    path('at/sources/<int:pk>/update/',
        login_required(views.ATSUpdateView.as_view()),
        name='ats_update'),
    path('nt/sources/<int:pk>/update/',
        login_required(views.NTSUpdateView.as_view()),
        name='nts_update'),
    path('at/vulns/<int:pk>/update/',
        login_required(views.VulnUpdateView.as_view()),
        name='vuln_update'),
    path('nt/conds/<int:pk>/update/',
        login_required(views.CondUpdateView.as_view()),
        name='cond_update'),
    path('impacts/<int:pk>/update/',
        login_required(views.ImpactUpdateView.as_view()),
        name='impact_update'),
    path('responses/<int:pk>/update/',
        login_required(views.ResponseUpdateView.as_view()),
        name='response_update'),
    path('at/events/<int:pk>/delete/',
        login_required(views.ATEDeleteView.as_view()),
        name='ate_delete'),
    path('nt/events/<int:pk>/delete/',
        login_required(views.NTEDeleteView.as_view()),
        name='nte_delete'),
    path('at/sources/<int:pk>/delete/',
        login_required(views.ATSDeleteView.as_view()),
        name='ats_delete'),
    path('nt/sources/<int:pk>/delete/',
        login_required(views.NTSDeleteView.as_view()),
        name='nts_delete'),
    path('at/vulns/<int:pk>/delete/',
        login_required(views.VulnDeleteView.as_view()),
        name='vuln_delete'),
    path('nt/conds/<int:pk>/delete/',
        login_required(views.CondDeleteView.as_view()),
        name='cond_delete'),
    path('impacts/<int:pk>/delete/',
        login_required(views.ImpactDeleteView.as_view()),
        name='impact_delete'),
    path('responses/<int:pk>/delete/',
        login_required(views.ResponseDeleteView.as_view()),
        name='response_delete'),
]

siem/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'siem'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('help/parsing/', login_required(views.parse_help),
        name='parse_help'),
    path('help/rules/', login_required(views.rule_help),
        name='rule_help'),
    path('help/events/', login_required(views.event_help),
        name='event_help'),
    path('help/daemons/', login_required(views.daemon_help),
        name='daemon_help'),
    path('help/regex/', login_required(views.regex_help),
        name='regex_help'),
    path('events/', login_required(views.event_index), name='event_index'),
    path('events/log/<int:pk>/', login_required(
        views.LogEventDetailView.as_view()), name='logevent_detail'),
    path('events/log/', login_required(
        views.LogEventSearchView.as_view()), name='logevent_search'),
    path('events/rule/', login_required(
        views.RuleEventSearchView.as_view()), name='ruleevent_search'),
    path('events/rule/<int:pk>/', login_required(
        views.RuleEventDetailView.as_view()), name='ruleevent_detail'),
    path('rules/limit/', login_required(
        views.LRIndexView.as_view()), name='lr_index'),
    path('rules/limit/<int:pk>/', login_required(
        views.LRDetailView.as_view()), name='lr_detail'),
    path('rules/limit/add/', login_required(
        views.LRCreateView.as_view()), name='lr_create'),
    path('rules/limit/<int:pk>/update/', login_required(
        views.LRUpdateView.as_view()), name='lr_update'),
    path('rules/limit/<int:pk>/delete/', login_required(
        views.LRDeleteView.as_view()), name='lr_delete'),
    path('parsers/log/', login_required(
        views.LPIndexView.as_view()), name='lp_index'),
    path('parsers/log/<int:pk>/', login_required(
        views.LPDetailView.as_view()), name='lp_detail'),
    path('parsers/log/add/', login_required(
        views.LPCreateView.as_view()), name='lp_create'),
    path('parsers/log/<int:pk>/update/', login_required(
        views.LPUpdateView.as_view()), name='lp_update'),
    path('parsers/log/<int:pk>/delete/', login_required(
        views.LPDeleteView.as_view()), name='lp_delete'),
    path('parsers/helpers/', login_required(
        views.PHIndexView.as_view()), name='ph_index'),
    path('parsers/helpers/<int:pk>/', login_required(
        views.PHDetailView.as_view()), name='ph_detail'),
    path('parsers/helpers/add/', login_required(
        views.PHCreateView.as_view()), name='ph_create'),
    path('parsers/helpers/<int:pk>/update/', login_required(
        views.PHUpdateView.as_view()), name='ph_update'),
    path('parsers/helpers/<int:pk>/delete/', login_required(
        views.PHDeleteView.as_view()), name='ph_delete'),
]

hwam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from hwam.choices import *

# Create your models here.

class OrganizationalUnit(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    unit_contact = models.ForeignKey(User,
            on_delete=models.PROTECT)
    parent_ou = models.ForeignKey('self',
            related_name='child_ous',
            null=True, blank=True, on_delete=models.CASCADE)
            #symmetrical=False)
    # To Do: Add permissions (read/create/edit/delete ou assets)
    def __str__(self):
        return self.absolute_name()
    def absolute_name(self):
        if self.parent_ou:
            return '/'.join((self.parent_ou.absolute_name(), self.name))
        else:
            return self.name
    absolute_name.admin_order_field = 'name'
    def children(self):
        return OrganizationalUnit.objects.filter(
                parent_ou=self.pk).order_by('name')
    def serializable_object(self):
        obj = {'name': self.name, 'children': []}
        for child in self.children():
            obj['children'].append(child.serializable_object())
        return obj

class HardwareClass(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return self.name

class HardwareCategory(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return '/'.join((self.hardware_class.name, self.name))
    hardware_class = models.ForeignKey(HardwareClass,
            related_name='hardware_categories',
            on_delete=models.PROTECT)

class HardwareType(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        val = (self.hardware_category.hardware_class.name,
                self.hardware_category.name, self.name)
        return '/'.join(val)
    hardware_category = models.ForeignKey(HardwareCategory,
            related_name='hardware_types',
            on_delete=models.PROTECT)

class HardwareAsset(models.Model):
    parent_hardware = models.ForeignKey('self',
            related_name='child_hardware',
            null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    org_unit = models.ForeignKey(OrganizationalUnit,
            related_name='hardware_assets',
            on_delete=models.PROTECT)
    # To Do: Add clearance level
    asset_owner = models.ForeignKey(User,
            related_name='hardware_assets_owned',
            null=True, blank=True, on_delete=models.SET_NULL)
    asset_custodian = models.ForeignKey(User,
            related_name='hardware_assets_cust',
            null=True, blank=True, on_delete=models.SET_NULL)
    hardware_type = models.ForeignKey(HardwareType,
            related_name='assets',
            null=True, blank=True, on_delete=models.SET_NULL)
    device_maker = models.CharField(max_length=20, null=True, blank=True)
    device_model = models.CharField(max_length=20, null=True, blank=True)
    property_id = models.CharField(max_length=30, null=True, blank=True)
    location = models.CharField(max_length=40, null=True, blank=True)
    status = models.IntegerField(choices=status_choices, default=6)
    date_added = models.DateField('date added', default=timezone.now,
            null=True, blank=True)
    date_eol = models.DateField('end of life', null=True, blank=True)
    def __str__(self):
        return self.name
    def is_active(self):
        return self.status == 1
    is_active.admin_order_field = 'status'
    is_active.boolean = True
    is_active.short_description = 'Active?'

class SoftwareCategory(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return self.name

class SoftwareType(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return '/'.join((self.software_category.name, self.name))
    software_category = models.ForeignKey(SoftwareCategory,
            related_name='software_types',
            on_delete=models.PROTECT)

class SoftwareAsset(models.Model):
    parent_hardware = models.ManyToManyField(HardwareAsset,
            related_name='child_software', blank=True)
    parent_software = models.ManyToManyField('self',
            related_name='child_software', blank=True,
            symmetrical=False)
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=200, null=True, blank=True)
    org_unit = models.ForeignKey(OrganizationalUnit,
            related_name='software_assets',
            on_delete=models.PROTECT)
    # To Do: Add clearance level
    custodian_swam = models.ForeignKey(User,
            related_name='systems_swam',
            null=True, blank=True, on_delete=models.SET_NULL)
    custodian_csm = models.ForeignKey(User,
            related_name='systems_csm',
            null=True, blank=True, on_delete=models.SET_NULL)
    custodian_vul = models.ForeignKey(User,
            related_name='systems_vul',
            null=True, blank=True, on_delete=models.SET_NULL)
    software_type = models.ForeignKey(SoftwareType,
            related_name='assets',
            null=True, blank=True, on_delete=models.SET_NULL)
    hostname = models.CharField(max_length=48, null=True, blank=True)
    domain_name = models.CharField(max_length=48, null=True, blank=True)
    ip4_address_1 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_2 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_3 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_4 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_5 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_6 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_7 = models.CharField(max_length=20, null=True, blank=True)
    ip4_address_8 = models.CharField(max_length=20, null=True, blank=True)
    ip6_address_1 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_2 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_3 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_4 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_5 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_6 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_7 = models.CharField(max_length=42, null=True, blank=True)
    ip6_address_8 = models.CharField(max_length=42, null=True, blank=True)
    package_vendor = models.CharField(max_length=32, null=True, blank=True)
    package_name = models.CharField(max_length=32, null=True, blank=True)
    package_version = models.CharField(max_length=20, null=True, blank=True)
    sw_property_id = models.CharField(max_length=30, null=True, blank=True)
    status = models.IntegerField(choices=status_choices, default=6)
    date_added = models.DateField('date added', default=timezone.now,
            null=True, blank=True)
    date_eol = models.DateField('end of life', null=True, blank=True)
    def __str__(self):
        return self.name
    def is_active(self):
        return self.status == 1
    is_active.admin_order_field = 'status'
    is_active.boolean = True
    is_active.short_description = 'Active?'

risk/templates/risk/advthreatevent_update_form.html
{% extends "risk/base.html" %}

{% block sub-title %}Update Adversarial Threat Event | {% endblock %}

{% block content-main %}

<h1>Update Adversarial Threat Event</h1>
{% if form.errors %}
<p>There were some errors.</p>

<ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.label_tag }}: {{ field.errors }}</li>
    {% endif %}
    {% endfor %}
</ul>

{% endif %}

<form action="" method="post">{% csrf_token %}
    <table>
        <tr>
            <th>Attribute</th><th>Setting</th><th class="left">Description</th>
        </tr>
        <tr>
            <td class="right">Name</td><td>{{ form.name }}</td><td>The threat event's name.</td>
        </tr>
        <tr>
            <td class="right">Desc</td><td>{{ form.desc }}</td><td>A description of the threat event.</td>
        </tr>
        <tr>
            <td class="right">Event Type</td><td>{{ form.event_type }}</td><td>The threat event type.</td>
        </tr>
        <tr>
            <td class="right">Sources</td><td>{{ form.sources }}</td><td>The threat sources related to this event.</td>
        </tr>
        <tr>
            <td class="right">Relevance</td><td>{{ form.relevance }}</td><td>The relevance of this threat event.</td>
        </tr>
        <tr>
            <td class="right">Info Source</td><td>{{ form.info_source }}</td><td>The source for information on this threat event.</td>
        </tr>
        <tr>
            <td class="right">Info Source Tier</td><td>{{ form.tier }}</td><td>The info source tier.</td>
        </tr>
        <tr>
            <td class="right">Likelihood of Initiation</td><td>{{ form.likelihood_initiation }}</td><td>The likelihood of this threat event being initiated.</td>
        </tr>
        <tr>
            <td class="right">Likelihood of Impact</td><td>{{ form.likelihood_impact }}</td><td>The likelihood of this threat event, if initiated, having an adverse impact.</td>
        </tr>
        <tr>
            <td class="right">Vulnerabilities</td><td>{{ form.vulnerabilities }}</td><td>Vulnerabilities related to this threat event.</td>
        </tr>
        <tr>
            <td class="right">Impacts</td><td>{{ form.impacts }}</td><td>Potential impacts of this threat event.</td>
        </tr>
        <tr>
            <td class="right">Responses</td><td>{{ form.responses }}</td><td>Precautions taken in response to this threat event.</td>
        </tr>
        <tr>
            <td class="right">Assigned Risk</td><td>{{ form.assigned_risk }}</td><td>The level of risk assigned to this threat event, after weighing the details.</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

risk/templates/risk/ate_detail.html
{% extends "risk/base.html" %}

{% block sub-title %}Adversarial Threat Event {{ ate }} | {% endblock %}

{% block content-main %}

<h1>{{ ate }} (Adversarial Threat Event)</h1>
<a href="{% url 'risk:ate_update' ate.id %}">Edit</a>
&middot;
<a href="{% url 'risk:ate_delete' ate.id %}">Delete</a>
&middot;
<a href="{% url 'risk:ate_index' %}">Index</a>

<p>{{ ate.desc }}</p>
<ul>
    <li>Type: {{ ate.event_type }}</li>
    <li>Info Source: {{ ate.info_source }}</li>
    <li>Info Tier: {{ate.get_tier_display }}</li>
    <li>Relevance: {{ ate.get_relevance_display }}</li>
    <li>Sources (capability/intent/targeting):<ul>
            {% for s in ate.sources.all %}
                <li><a href="{% url 'risk:ats_detail' s.id %}">{{ s }}
                        ({{ s.capability }}/{{ s.intent }}/{{ s.targeting }})</a></li>
            {% endfor %}
        </ul></li>
    <li>Vulnerabilities (severity):<ul>
            {% for v in ate.vulnerabilities.all %}
                <li><a href="{% url 'risk:vuln_detail' v.id %}">{{ v }}
                        ({{ v.severity }})</a></li>
            {% endfor %}
        </ul></li>
    <li>Responses (effectiveness/status):<ul>
            {% for r in ate.responses.all %}
                <li><a href="{% url 'risk:response_detail' r.id %}">{{ r }}
                    ({{ r.effectiveness }}/{{ r.get_status_display }})</a></li>
            {% endfor %}
        </ul></li>
    <li>Likelihoods:<ul>
            <li>Likelihood of initiation: {{ ate.likelihood_initiation }}</li>
            <li>Likelihood of adverse impact: {{ ate.likelihood_impact }}</li>
            <li>Calculated Likelihood: {{ ate.calc_likelihood }}</li>
        </ul></li>
    <li>Impacts (severity/impact tier):<ul>
            {% for i in ate.impacts.all %}
                <li><a href="{% url 'risk:impact_detail' i.id %}">{{ i }}
                        ({{ i.severity }}/{{ i.get_impact_tier_display }})</a></li>
            {% endfor %}
        </ul></li>
    <li>Assigned Risk: {{ ate.assigned_risk }}</li>
</ul>

{% endblock %}

risk/templates/risk/ats_delete.html
{% extends "risk/base.html" %}

{% block sub-title %}Delete Adversarial Threat Source | {% endblock %}

{% block content-main %}

<h1>Delete Adversarial Threat Source</h1>

<p>Are you sure you want to delete {{ ats }}?</p>

<form action="{% url 'risk:ats_delete' ats.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'risk:ats_detail' ats.id %}">Cancel</a>
</form>

{% endblock %}

risk/templates/risk/ats_index.html
{% extends "risk/base.html" %}

{% block sub-title %}Adversarial Threat Sources | {% endblock %}

{% block content-main %}

<h1>Adversarial Threat Sources</h1>
<a href="{% url 'risk:ats_create' %}">Add</a>

{% if ats_list %}
    <ul>
        {% for ats in ats_list %}
            <li><a href="{% url 'risk:ats_detail' ats.id %}">
                    {{ ats }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No adversarial threat sources.</p>
{% endif %}

{% endblock %}

risk/templates/risk/impact_detail.html
{% extends "risk/base.html" %}

{% block sub-title %}Impact - {{ impact }} | {% endblock %}

{% block content-main %}

<h1>{{ impact }} (Impact)</h1>
<a href="{% url 'risk:impact_update' impact.id %}">Edit</a>
&middot;
<a href="{% url 'risk:impact_delete' impact.id %}">Delete</a>
&middot;
<a href="{% url 'risk:impact_index' %}">Index</a>

<p>{{ impact.desc }}</p>

<ul>
    <li>Impact Type: {{ impact.impact_type }}</li>
    <li>Information Source: {{ impact.info_source }}</li>
    <li>Info Source Tier: {{ impact.tier }}</li>
    <li>Severity (1-100): {{ impact.severity }}</li>
    <li>Impact Tier: {{ impact.impact_tier }}</li>
</ul>

{% endblock %}

risk/templates/risk/nte_delete.html
{% extends "risk/base.html" %}

{% block sub-title %}Delete Non-Adversarial Threat Source | {% endblock %}

{% block content-main %}

<h1>Delete Non-Adversarial Threat Event</h1>

<p>Are you sure you want to delete {{ nte }}?</p>

<form action="{% url 'risk:ate_delete' nte.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'risk:nte_detail' nte.id %}">Cancel</a>
</form>

{% endblock %}

risk/templates/risk/nts_delete.html
{% extends "risk/base.html" %}

{% block sub-title %}Delete Non-Adversarial Threat Source | {% endblock %}

{% block content-main %}

<h1>Delete Non-Adversarial Threat Source</h1>

<p>Are you sure you want to delete {{ nts }}?</p>

<form action="{% url 'risk:ats_delete' nts.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'risk:nts_detail' nts.id %}">Cancel</a>
</form>

{% endblock %}

risk/templates/risk/nts_index.html
{% extends "risk/base.html" %}

{% block sub-title %}Non-Adversarial Threat Sources | {% endblock %}

{% block content-main %}

<h1>Non-Adversarial Threat Sources</h1>
<a href="{% url 'risk:nts_create' %}">Add</a>

{% if nts_list %}
    <ul>
        {% for nts in nts_list %}
            <li><a href="{% url 'risk:nts_detail' nts.id %}">
                    {{ nts }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No non-adversarial threat sources.</p>
{% endif %}

{% endblock %}

risk/templates/risk/riskcondition_form.html
{% extends "risk/base.html" %}

{% block sub-title %}Add Condition | {% endblock %}

{% block content-main %}

<h1>Add Condition</h1>
{% if form.errors %}
<p>There were some errors.</p>

<ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.label_tag }}: {{ field.errors }}</li>
    {% endif %}
    {% endfor %}
</ul>

{% endif %}

<form action="" method="post">{% csrf_token %}
    <table>
        <tr>
            <th>Attribute</th><th>Setting</th><th class="left">Description</th>
        </tr>
        <tr>
            <td class="right">Name</td><td>{{ form.name }}</td><td>The condition's name.</td>
        </tr>
        <tr>
            <td class="right">Desc</td><td>{{ form.desc }}</td><td>A description of the condition.</td>
        </tr>
        <tr>
            <td class="right">Type</td><td>{{ form.condition_type }}</td><td>The condition type.</td>
        </tr>
        <tr>
            <td class="right">Info Source</td><td>{{ form.info_source }}</td><td>The source for information on this condition.</td>
        </tr>
        <tr>
            <td class="right">Info Source Tier</td><td>{{ form.tier }}</td><td>The info source tier.</td>
        </tr>
        <tr>
            <td class="right">Pervasiveness</td><td>{{ form.pervasiveness }}</td><td>The pervasiveness of this condition.</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

risk/templates/risk/vuln_detail.html
{% extends "risk/base.html" %}

{% block sub-title %}Vulnerability - {{ vuln }} | {% endblock %}

{% block content-main %}

<h1>{{ vuln }} (Vulnerability)</h1>
<a href="{% url 'risk:vuln_update' vuln.id %}">Edit</a>
&middot;
<a href="{% url 'risk:vuln_delete' vuln.id %}">Delete</a>
&middot;
<a href="{% url 'risk:response_index' %}">Index</a>

<p>{{ vuln.desc }}</p>

<ul>
    <li>Vulnerability Type: {{ vuln.vuln_type }}</li>
    <li>Severity (1-100): {{ vuln.severity }}</li>
    <li>Information Source: {{ vuln.info_source }}</li>
    <li>Info Source Tier: {{ vuln.tier }}</li>
</ul>

{% endblock %}